"""update(client): replace datetime.utcnow instead of datetime.now in created_at and updated_at columns

Revision ID: 945fe9734b2e
Revises: f2e36daa4c25
Create Date: 2026-10-09 17:21:31.484793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945fe9734b2e'
down_revision: Union[str, Sequence[str], None] = 'f2e36daa4c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
