"""add unique to columns in clients table

Revision ID: a9c7ddd42782
Revises: 2d82c2f278b9
Create Date: 2026-10-07 20:13:08.087724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c7ddd42782'
down_revision: Union[str, Sequence[str], None] = '2d82c2f278b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_unique_constraint(None, 'clients', ['phone_number'])
    op.create_unique_constraint(None, 'clients', ['company'])
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    # ### end Alembic commands ###
