"""add relationship to users and clients tables

Revision ID: f2e36daa4c25
Revises: a9c7ddd42782
Create Date: 2026-10-08 22:55:22.577841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e36daa4c25'
down_revision: Union[str, Sequence[str], None] = 'a9c7ddd42782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('clients', 'phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('clients_company_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_phone_number_key'), 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_index('user_client_company', 'clients', ['user_id', 'company'], unique=True, postgresql_where=sa.text('company IS NOT NULL'))
    op.create_index('user_client_email', 'clients', ['user_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_unique_constraint('user_client_name', 'clients', ['user_id', 'name'])
    op.create_unique_constraint('user_client_phone_number', 'clients', ['user_id', 'phone_number'])
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint('user_client_phone_number', 'clients', type_='unique')
    op.drop_constraint('user_client_name', 'clients', type_='unique')
    op.drop_index('user_client_email', table_name='clients', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('user_client_company', table_name='clients', postgresql_where=sa.text('company IS NOT NULL'))
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_unique_constraint(op.f('clients_phone_number_key'), 'clients', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_company_key'), 'clients', ['company'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'phone_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
